version: '3.8'

services:
  nestjs-prod:
    container_name: nestjs-prod-app
    image: nestjs-prod:latest
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: runner
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3001}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3001}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
