version: '3.8'

services:
  nestjs-dev:
    container_name: nestjs-dev-app
    image: nestjs-dev:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3001}
    command: pnpm run start:dev
    restart: unless-stopped